#### 1- Find record if Sales greater than 500 and Quantity greater than 5?

In [9]:
import pandas as pd

In [10]:
df = pd.read_csv("retail supermarket.csv")
df

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,25.2480,3,0.20,4.1028
9990,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,91.9600,2,0.00,15.6332
9991,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,258.5760,2,0.20,19.3932
9992,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,29.6000,4,0.00,13.3200
9993,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,243.1600,2,0.00,72.9480

In [12]:
df[(df["Sales"] > 500) & (df["Quantity"] > 5)]

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
7,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,907.152,6,0.2,90.7152
10,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,1706.184,9,0.2,85.3092
16,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,665.880,6,0.0,13.3176
27,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19140,East,Furniture,Bookcases,3083.430,7,0.5,-1665.0522
35,First Class,Corporate,United States,Richardson,Texas,75080,Central,Technology,Phones,1097.544,7,0.2,123.4737
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9879,Standard Class,Consumer,United States,New York City,New York,10035,East,Furniture,Chairs,573.174,7,0.1,63.6860
9925,First Class,Corporate,United States,New York City,New York,10035,East,Office Supplies,Binders,1087.936,8,0.2,353.5792
9942,Standard Class,Consumer,United States,Anaheim,California,92804,West,Office Supplies,Storage,998.820,9,0.0,29.9646
9947,Second Class,Corporate,United States,Indianapolis,Indiana,46203,Central,Furniture,Chairs,1925.880,6,0.0,539.2464
9948,Second Class,Corporate,United States,Indianapolis,Indiana,46203,Central,Office Supplies,Appliances,2405.200,8,0.0,793.7160

#### 2- Find records if Discount is more than 0.5 (50%) or Profit is negative.

In [13]:
df[(df["Discount"] > 0.5) & (df["Profit"] < 0)]

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
14,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,68.810,5,0.8,-123.8580
15,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Binders,2.544,3,0.8,-3.8160
28,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19140,East,Office Supplies,Binders,9.618,2,0.7,-7.0532
32,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19140,East,Office Supplies,Binders,6.858,6,0.7,-5.7150
36,First Class,Corporate,United States,Richardson,Texas,75080,Central,Furniture,Furnishings,190.920,5,0.6,-147.9630
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9870,First Class,Corporate,United States,Mason,Ohio,45040,East,Office Supplies,Binders,22.428,3,0.7,-17.9424
9877,First Class,Home Office,United States,Cleveland,Ohio,44105,East,Office Supplies,Binders,8.700,5,0.7,-6.3800
9903,Standard Class,Consumer,United States,Carrollton,Texas,75007,Central,Furniture,Furnishings,25.128,3,0.6,-6.9102
9920,Standard Class,Corporate,United States,Bryan,Texas,77803,Central,Office Supplies,Binders,22.386,7,0.8,-35.8176
9921,Standard Class,Home Office,United States,Akron,Ohio,44312,East,Office Supplies,Binders,5.742,3,0.7,-4.5936

#### 3- Display Ship Mode and Profit columns if region is East using loc

In [15]:
df.loc[df['Region'] == 'East', ['Ship Mode', 'Profit']]

           Ship Mode     Profit
23      Second Class    -1.0196
27    Standard Class -1665.0522
28    Standard Class    -7.0532
29    Standard Class    15.5250
30    Standard Class     1.1016
...              ...        ...
9968  Standard Class   331.1910
9969  Standard Class     6.5975
9981     First Class     5.3690
9984  Standard Class    15.1200
9985  Standard Class    16.1240

[2848 rows x 2 columns]

#### 4- How many records belong to the "Corporate" segment and the "Central" region?

In [16]:
len(df[(df['Segment'] == 'Corporate') & (df['Region'] == 'Central')])

673

#### 5- Find all orders in the "Furniture" category but not in "Chairs" sub-category.

In [17]:
df[(df['Category'] == 'Furniture') & (df['Sub-Category'] != 'Chairs')]

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
5,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,48.8600,7,0.00,14.1694
10,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,1706.1840,9,0.20,85.3092
24,Standard Class,Consumer,United States,Orem,Utah,84057,West,Furniture,Tables,1044.6300,3,0.00,240.2649
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9962,First Class,Home Office,United States,Houston,Texas,77041,Central,Furniture,Bookcases,383.4656,4,0.32,-67.6704
9964,Second Class,Corporate,United States,Newark,Delaware,19711,East,Furniture,Furnishings,13.4000,1,0.00,6.4320
9980,Second Class,Consumer,United States,Lafayette,Louisiana,70506,South,Furniture,Tables,85.9800,1,0.00,22.3548
9989,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,25.2480,3,0.20,4.1028
9990,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,91.9600,2,0.00,15.6332

#### 6- Which orders have discount (>0.3) and still earned profit (>0)?

In [19]:
df[(df["Discount"] < 0.3) & (df["Profit"] > 0)]

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.960,2,0.0,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.940,3,0.0,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.620,2,0.0,6.8714
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.368,2,0.2,2.5164
5,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,48.860,7,0.0,14.1694
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,25.248,3,0.2,4.1028
9990,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,91.960,2,0.0,15.6332
9991,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,258.576,2,0.2,19.3932
9992,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,29.600,4,0.0,13.3200
9993,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,243.160,2,0.0,72.9480

#### 7- Find high-profit orders where Quantity > 5 and Category == 'Technology'.

In [20]:
df[(df["Quantity"] > 5) & (df["Category"] == "Technology")]

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
7,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,907.152,6,0.2,90.7152
35,First Class,Corporate,United States,Richardson,Texas,75080,Central,Technology,Phones,1097.544,7,0.2,123.4737
103,Standard Class,Consumer,United States,Aurora,Colorado,80013,West,Technology,Accessories,238.896,6,0.2,-26.8758
106,Standard Class,Consumer,United States,Charlotte,North Carolina,28205,South,Technology,Accessories,74.112,8,0.2,17.6016
123,First Class,Consumer,United States,Wilmington,Delaware,19805,East,Technology,Phones,68.040,7,0.0,19.7316
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9840,Standard Class,Consumer,United States,Long Beach,California,90805,West,Technology,Phones,44.736,8,0.2,4.4736
9882,First Class,Consumer,United States,Woodstock,Georgia,30188,South,Technology,Accessories,272.610,13,0.0,98.1396
9891,Second Class,Corporate,United States,Milwaukee,Wisconsin,53209,Central,Technology,Accessories,124.250,7,0.0,48.4575
9895,Standard Class,Consumer,United States,Chicago,Illinois,60623,Central,Technology,Accessories,153.824,11,0.2,38.4560
9941,Standard Class,Consumer,United States,San Francisco,California,94122,West,Technology,Accessories,223.580,14,0.0,87.1962

#### 8- Select rows 0–4 and columns 'Ship Mode', 'Segment', 'Sales' by position using iloc

In [23]:
df.iloc[0:5, [0, 1, 9]]

        Ship Mode    Segment     Sales
0    Second Class   Consumer  261.9600
1    Second Class   Consumer  731.9400
2    Second Class  Corporate   14.6200
3  Standard Class   Consumer  957.5775
4  Standard Class   Consumer   22.3680

#### 9- Show Home Office segment orders with Sales > 1000 and Quantity > 3.

In [24]:
df[(df['Segment'] == 'Home Office') & (df['Sales'] > 1000) & (df['Quantity'] > 3)]

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
244,Second Class,Home Office,United States,Lakeville,Minnesota,55044,Central,Furniture,Chairs,2001.860,7,0.0,580.5394
247,Second Class,Home Office,United States,Lakeville,Minnesota,55044,Central,Office Supplies,Appliances,1503.250,5,0.0,496.0725
353,First Class,Home Office,United States,New York City,New York,10009,East,Office Supplies,Binders,4355.168,4,0.2,1415.4296
463,Standard Class,Home Office,United States,Phoenix,Arizona,85023,West,Furniture,Tables,1272.630,6,0.5,-814.4832
515,Standard Class,Home Office,United States,Great Falls,Montana,59405,West,Technology,Copiers,2999.950,5,0.0,1379.9770
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8890,Second Class,Home Office,United States,Columbia,Missouri,65203,Central,Office Supplies,Appliances,1927.590,7,0.0,751.7601
8892,Standard Class,Home Office,United States,San Diego,California,92037,West,Furniture,Chairs,2676.672,9,0.2,267.6672
9056,First Class,Home Office,United States,New York City,New York,10011,East,Furniture,Chairs,2621.322,11,0.1,553.3902
9660,Standard Class,Home Office,United States,Santa Barbara,California,93101,West,Technology,Phones,3023.928,9,0.2,226.7946
9673,Standard Class,Home Office,United States,Philadelphia,Pennsylvania,19143,East,Technology,Phones,1499.970,5,0.4,-374.9925

#### 10- Find orders where Profit Margin > 0.3
##### Profit Margin = (Profit/Sales)

In [25]:
df[(df['Profit'] / df['Sales']) > 0.3]

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.620,2,0.0,6.8714
8,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,18.504,3,0.2,5.7825
12,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,15.552,3,0.2,5.4432
13,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,407.976,3,0.2,132.5922
20,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Binders,22.720,4,0.2,7.3840
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9982,Standard Class,Consumer,United States,Grand Rapids,Michigan,49505,Central,Office Supplies,Paper,35.560,7,0.0,16.7132
9984,Standard Class,Consumer,United States,Long Beach,New York,11561,East,Office Supplies,Labels,31.500,10,0.0,15.1200
9986,Standard Class,Consumer,United States,Los Angeles,California,90008,West,Technology,Accessories,36.240,1,0.0,15.2208
9987,Standard Class,Corporate,United States,Athens,Georgia,30605,South,Technology,Accessories,79.990,1,0.0,28.7964
9992,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,29.600,4,0.0,13.3200